# Generated by Django 6.0.4 on 2026-08-21 10:10

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_businesshour_time_zone_alter_company_time_zone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horillauser",
            name="number_grouping",
        ),
        migrations.RemoveField(
            model_name="multiplecurrency",
            name="format",
        ),
        migrations.AddField(
            model_name="horillauser",
            name="number_format",
            field=models.CharField(
                choices=[
                    ("western_format", "Western - 1,234,567.89"),
                    ("european_format", "European - 1.234.567,89"),
                    ("space_format", "Space Separated - 1 234 567,89"),
                    ("indian_format", "Indian - 12,34,567.89"),
                ],
                default="western_format",
                help_text="Select your preferred number format.",
                max_length=20,
                verbose_name="Number Format",
            ),
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="week_days",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=27,
                verbose_name="Week days",
            ),
        ),
        migrations.AlterField(
            model_name="shifthour",
            name="week_days",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=27,
                verbose_name="Week days",
            ),
        ),
    ]
