# Generated by Django 6.0.4 on 2026-09-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicates', '0002_alter_duplicaterule_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicaterule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='duplicaterule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='duplicaterulecondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='duplicaterulecondition',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='matchingrulecriteria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='matchingrulecriteria',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
    ]
