# Generated by Django 6.0.4 on 2026-09-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_alter_customcalendar_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalendarpreference',
            name='calendar_type',
            field=models.CharField(choices=[('task', 'Task'), ('event', 'Event'), ('meeting', 'Meeting'), ('unavailability', 'Un Availability'), ('status_completed', 'Completed'), ('status_pending', 'Not completed')], max_length=20, verbose_name='Calendar Type'),
        ),
    ]
