# Generated by Django 6.0.4 on 2026-09-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_componentcriteria_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentcriteria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='componentcriteria',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Default'),
        ),
        migrations.AlterField(
            model_name='dashboardcomponent',
            name='component_type',
            field=models.CharField(choices=[('chart', 'Charts'), ('table_data', 'Table Data'), ('kpi', 'KPI')], db_index=True, max_length=50, verbose_name='Component Type'),
        ),
        migrations.AlterField(
            model_name='dashboardcomponent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dashboardcomponent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='dashboardfolder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dashboardfolder',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
    ]
