# Generated by Django 6.0.4 on 2026-09-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_alter_horillamail_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horillamail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='horillamail',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='horillamail',
            name='mail_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='horillamail',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the mail should be sent (for scheduled mails).', null=True),
        ),
        migrations.AlterField(
            model_name='horillamailattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='horillamailattachment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Primary Mail Server'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='mail_channel',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], db_index=True, help_text='Specifies whether this configuration handles incoming,outgoing, or both types of emails.', max_length=20, verbose_name='Mail Channel'),
        ),
        migrations.AlterField(
            model_name='horillamailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='horillamailtemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
    ]
