# Generated by Django 6.0.4 on 2026-09-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0007_alter_horillamail_mail_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horillamailconfiguration",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Display Name"
            ),
        ),
    ]
