# Generated by Django 6.0.4 on 2026-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_fields", "0002_alter_customfielddefinition_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfielddefinition",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("small_text", "Small Text"),
                    ("large_text", "Large Text"),
                    ("number", "Number"),
                    ("choice", "Multiple Choice"),
                    ("single_choice", "Single Choice"),
                ],
                max_length=20,
                verbose_name="Field Type",
            ),
        ),
    ]
