# Generated by Django 6.0.4 on 2026-09-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_alter_opportunityteammember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultopportunitymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='defaultopportunitymember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='close_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Close Date'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='forecast_category',
            field=models.CharField(blank=True, choices=[('omitted', 'Omitted'), ('pipeline', 'Pipeline'), ('best_case', 'Best Case'), ('commit', 'Commit'), ('closed', 'Closed')], db_index=True, max_length=50, verbose_name='Forecast Category'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='opportunitycontactrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='opportunitycontactrole',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='opportunitysettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='opportunitysettings',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='opportunitysplit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='opportunitysplit',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='opportunitysplittype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='opportunitysplittype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='opportunitystage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='opportunitystage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='opportunitystage',
            name='is_final',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Final Stage'),
        ),
        migrations.AlterField(
            model_name='opportunitystage',
            name='stage_type',
            field=models.CharField(choices=[('open', 'Open'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], db_index=True, default='open', help_text='Type of stage - Open, Closed Won, or Closed Lost', max_length=10, verbose_name='Stage Type'),
        ),
        migrations.AlterField(
            model_name='opportunityteam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='opportunityteam',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='opportunityteammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='opportunityteammember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
    ]
