# Generated by Django 6.0.4 on 2026-09-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_alter_emailtoleadconfig_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="lead_company",
            field=models.CharField(max_length=100, verbose_name="Lead Company"),
        ),
    ]
