# Generated by Django 6.0.4 on 2026-09-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0004_alter_automationcondition_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horillaautomation",
            name="schedule_run_time",
            field=models.TimeField(
                blank=True,
                help_text="The time of day to run the automation. Leave empty to run whenever the scheduler runs.",
                null=True,
                verbose_name="Run Time",
            ),
        ),
    ]
